### ISSUE TITLE
bug in raycast vehicle demo

### ISSUE THREAD

**Issue by codz01** [BeRo1985/kraft#27]
![GIF 23-01-2023 17-17-44](https://user-images.githubusercontent.com/10813427/214091844-075077cb-7bea-4abf-af6b-636c3b2c3998.gif)

**Comment by BeRo1985** [comment]
Hm, I've fixed it actually with the last commits from the last days. Which compiler you're using and which version and for which CPU, and for which OS, and with with optimization options?

**Comment by BeRo1985** [comment]
Can you try undefine all {$define SIMD} in the kraft.pas ?

**Comment by BeRo1985** [comment]
FPC seems to have problems when a function result is also a function argument  at the same time, regarding a creating a shadow temporary target for the result, or something. for example at `a := Vector3Add(a, b);`  or  `a := Vector3Add(b, a);` 

at least I've workarounded it so far now for my own local FPC version build, by finetuned the function argument parameters per IFDEFs, for decide depending on the build-variant either if const or constref is used here, and for Delphi is only const used, since Delphi doesn't know constref. See the latest commits from the last days.

**Comment by BeRo1985** [comment]
Okay, please test with https://github.com/BeRo1985/kraft/commit/d52968dca2b38d430cef4ba302fd67302ba7bb73 again

**Comment by codz01** [comment]
thanks , yes it works now without problems

**Comment by BeRo1985** [comment]
Okay good :-)

**Comment by codz01** [comment]
forgot to mention my build system ;)
![kraft](https://user-images.githubusercontent.com/10813427/214618409-442c79cd-e214-46dc-9cb2-5fc55e45514e.jpg)

optimization was -O3  only
